#!/bin/zsh

echo "Installing oh my zsh configs"
rm ~/.zprofile
rm ~/.zshrc
ln -s $PWD/zsh/zprofile ~/.zprofile
ln -s $PWD/zsh/zshrc ~/.zshrc

echo "Installing bin"
rm -rf ~/bin
mkdir ~/bin

cp -R $PWD/bin/* ~/bin
ln -s $PWD/zsh/functions.zsh ~/bin/functions.zsh

# echo "Installing Vim configs"
# rm ~/.vimrc
# ln -s $PWD/vim/vimrc ~/.vimrc

# rm ~/.vimrc.bundles
# ln -s $PWD/vim/vimrc.bundles ~/.vimrc.bundles

# rm -f ~/.vim/autoload/plug.vim
# curl -fLo ~/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Git configs"
rm -f ~/.gitconfig
ln -s $PWD/git/gitconfig ~/.gitconfig

rm -f ~/.gitignore
ln -s $PWD/git/gitignore ~/.gitignore

echo "Installing IEx configs"
rm -f ~/.iex.exs
ln -s $PWD/elixir/iex.exs ~/.iex.exs
